*&---------------------------------------------------------------------*
*& Include ZBC405_A20_M01_TOP                       - Report ZBC405_A20_M01
*&---------------------------------------------------------------------*
REPORT zbc405_a20_m01.

"PARAMETERS
PARAMETERS : p_car  TYPE sflight-carrid MODIF ID gr1, " VALUE CHECK,
             p_con1 TYPE sflight-connid MODIF ID gr1,
             p_fld1 TYPE sflight-fldate MODIF ID gr1.

"List
DATA : gt_sfli TYPE TABLE OF sflight,
       gc_mark VALUE 'X',
       gv_chg.

"select-options
*SELECT-OPTIONS <변수명> FOR <기선언된 변수명>.
TABLES: sflight, sscrfields.
*
SELECT-OPTIONS so_fld FOR sflight-fldate.
*SELECT-OPTIONS so_fld2 FOR p_fld1 NO-EXTENSION.
*SELECTION-SCREEN COMMENT 1(10) FOR FIELD p_fld2.
*PARAMETERS p_fld2 TYPE sflight-fldate.

SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT 1(10) FOR FIELD cb_popup. "파라미터의 이름이 어디에 적힐지 지정
*  SELECTION-SCREEN POSITION 50. "입력 파라미터의 위치 지정
  PARAMETERS cb_popup AS CHECKBOX.
SELECTION-SCREEN END OF LINE.

"Detail 버튼
SELECTION-SCREEN SKIP 1.
SELECTION-SCREEN PUSHBUTTON 1(10) gv_text USER-COMMAND on.


SELECTION-SCREEN SKIP 3.
SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT 1(10) TEXT-t10.
*  PARAMETERS p_car10 AS CHECKBOX.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN ULINE.
SELECTION-SCREEN SKIP 1.

SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT 4(6) TEXT-t05 FOR FIELD pa_rad1.
  SELECTION-SCREEN POSITION 11.
  PARAMETERS pa_rad1 RADIOBUTTON GROUP gr1 MODIF ID gr1.
  SELECTION-SCREEN  COMMENT pos_low(15) FOR FIELD  pa_rad2.
  PARAMETERS pa_rad2 RADIOBUTTON GROUP gr1 MODIF ID gr1.
  SELECTION-SCREEN  COMMENT pos_high(15) FOR FIELD pa_rad3.
  PARAMETERS pa_rad3 RADIOBUTTON GROUP gr1 MODIF ID gr1.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN SKIP 2.
SELECTION-SCREEN ULINE.



SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT 1(10) TEXT-t05.
  PARAMETERS pa_rad11 RADIOBUTTON GROUP rd1 MODIF ID gr1.
  SELECTION-SCREEN  COMMENT pos_low(15) TEXT-t06.
  PARAMETERS pa_rad12 RADIOBUTTON GROUP rd1.
  SELECTION-SCREEN  COMMENT pos_high(15) TEXT-t07.
  PARAMETERS pa_rad13 RADIOBUTTON GROUP rd1.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT 1(10) TEXT-t05.
  PARAMETERS pa_rad21 RADIOBUTTON GROUP rd1.
*  SELECTION-SCREEN  COMMENT pos_low(15) FOR FIELD  pa_rad2.

*  SELECTION-SCREEN POSITION 18.
  SELECTION-SCREEN COMMENT 20(10) FOR FIELD pa_rad22.
  SELECTION-SCREEN POSITION 18.
  PARAMETERS pa_rad22 RADIOBUTTON GROUP rd1.
*  SELECTION-SCREEN  COMMENT pos_high(15) FOR FIELD pa_rad3.
  SELECTION-SCREEN POSITION POS_HIGH.
  PARAMETERS pa_rad23 RADIOBUTTON GROUP rd1.
SELECTION-SCREEN END OF LINE.

*
*"POPUP SELECTION SCREEN
*SELECTION-SCREEN BEGIN OF SCREEN 1100.
*  PARAMETERS pa_car TYPE sflight-carrid.
*SELECTION-SCREEN END OF SCREEN 1100.
*
"SUB SCREEN
SELECTION-SCREEN BEGIN OF SCREEN 1200 AS SUBSCREEN.
  PARAMETERS pa_car11 TYPE sflight-carrid.
SELECTION-SCREEN END OF SCREEN 1200.

"SUB SCREEN
SELECTION-SCREEN BEGIN OF SCREEN 1300 AS SUBSCREEN.
  PARAMETERS pa_con12 TYPE sflight-connid.

SELECTION-SCREEN END OF SCREEN 1300.

"SUB SCREEN
SELECTION-SCREEN BEGIN OF SCREEN 1400 AS SUBSCREEN.
  SELECT-OPTIONS so_fld13 FOR sflight-fldatE MODIF ID gr1.
*  SELECTION-SCREEN PUSHBUTTON /1(10) gv_text USER-COMMAND on.
SELECTION-SCREEN END OF SCREEN 1400.

SELECTION-SCREEN BEGIN OF TABBED BLOCK ts_con FOR 5 LINES.
  SELECTION-SCREEN TAB (10) tab1 USER-COMMAND car DEFAULT SCREEN 1200.
  SELECTION-SCREEN TAB (10) tab2 USER-COMMAND con DEFAULT SCREEN 1300.
  SELECTION-SCREEN TAB (10) tab3 USER-COMMAND fld DEFAULT SCREEN 1400.
SELECTION-SCREEN END OF BLOCK ts_con.
