*---------------------------------------------------------------------*
*    view related data declarations
*---------------------------------------------------------------------*
*...processing: ZVSA20SAPLANE...................................*
TABLES: ZVSA20SAPLANE, *ZVSA20SAPLANE. "view work areas
CONTROLS: TCTRL_ZVSA20SAPLANE
TYPE TABLEVIEW USING SCREEN '0040'.
DATA: BEGIN OF STATUS_ZVSA20SAPLANE. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVSA20SAPLANE.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVSA20SAPLANE_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVSA20SAPLANE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVSA20SAPLANE_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVSA20SAPLANE_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVSA20SAPLANE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVSA20SAPLANE_TOTAL.

*...processing: ZVSA20SCARR.....................................*
TABLES: ZVSA20SCARR, *ZVSA20SCARR. "view work areas
CONTROLS: TCTRL_ZVSA20SCARR
TYPE TABLEVIEW USING SCREEN '0020'.
DATA: BEGIN OF STATUS_ZVSA20SCARR. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVSA20SCARR.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVSA20SCARR_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVSA20SCARR.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVSA20SCARR_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVSA20SCARR_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVSA20SCARR.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVSA20SCARR_TOTAL.

*...processing: ZVSA20SFLIGHT...................................*
TABLES: ZVSA20SFLIGHT, *ZVSA20SFLIGHT. "view work areas
CONTROLS: TCTRL_ZVSA20SFLIGHT
TYPE TABLEVIEW USING SCREEN '0030'.
DATA: BEGIN OF STATUS_ZVSA20SFLIGHT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVSA20SFLIGHT.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVSA20SFLIGHT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVSA20SFLIGHT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVSA20SFLIGHT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVSA20SFLIGHT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVSA20SFLIGHT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVSA20SFLIGHT_TOTAL.

*...processing: ZVSA20SPFLI.....................................*
TABLES: ZVSA20SPFLI, *ZVSA20SPFLI. "view work areas
CONTROLS: TCTRL_ZVSA20SPFLI
TYPE TABLEVIEW USING SCREEN '0010'.
DATA: BEGIN OF STATUS_ZVSA20SPFLI. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVSA20SPFLI.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVSA20SPFLI_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVSA20SPFLI.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVSA20SPFLI_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVSA20SPFLI_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVSA20SPFLI.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVSA20SPFLI_TOTAL.

*.........table declarations:.................................*
TABLES: ZTSAPLANE_A20                  .
TABLES: ZTSCARR_A20                    .
TABLES: ZTSFLIGHT_A20                  .
TABLES: ZTSPFLI_A20                    .
